version: '3.9'
services:
  comment_service_db:
    container_name: comment_service_db
    image: postgres:latest
    volumes:
      - comment_service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - shared_network
      - comment_service_network

  comment_service:
    container_name: comment_service
    image: comment-service:latest
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: comments
      SPRING_DATASOURCE_URL: jdbc:postgresql://comment_service_db:5432/comments
    depends_on:
      comment_service_db:
        condition: service_healthy
    networks:
      - shared_network
      - comment_service_network

networks:
  shared_network:
    external: true
  comment_service_network:
    driver: bridge

volumes:
  comment_service_data: