version: '3'
services:
  app:
    image: post-service:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: posts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  rabbitmq:
    image: rabbitmq:3.12.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db-data:



