spring:
  application:
    name: posts
  config:
    import: optional:configserver:http://localhost:8888
rabbitmq:
  queue:
    name: "post-service"
  exchange:
    name: "post-service-exchange"
  routing:
    key: "post-service-routing"
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus