azure:
  storage:
    container:
      name: images
    connection:
      string: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;

spring:
  application:
    name: posts
  config:
    import: optional:configserver:http://localhost:8888
rabbitmq:
  queue:
    name: "post-service"
  exchange:
    name: "post-service-exchange"
  routing:
    key: "post-service-routing"
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus