version: '3.9'
services:
  user_service_db:
    container_name: user_service_db
    image: postgres:latest
    volumes:
      - user_service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - shared_network
      - user_service_network

  user_service:
    container_name: user_service
    image: user-service:latest
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
      SPRING_DATASOURCE_URL: jdbc:postgresql://user_service_db:5432/users
    depends_on:
      user_service_db:
        condition: service_healthy
    networks:
      - shared_network
      - user_service_network

networks:
  shared_network:
    external: true
  user_service_network:
    driver: bridge

volumes:
  user_service_data:


