eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
azure:
  blob-storage:
    connection-string:

spring:
  cloud:
    azure:
      storage:
        blob:
          container-name: images

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: posts
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/posts
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
