name: Comment Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'comment-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'comment-service/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/checkout@v4
      - name: Build and Test for Comment Service
        run: |
          echo "Building and testing Comment Service..."
          cd comment-service
          mvn -B package --file pom.xml