name: Config Server CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'config-server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'config-server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Test for Config Server
        run: |
          echo "Building and testing Config Server..."
          cd config-server
          mvn -B package --file pom.xml