name: Config Server CI/CD

on:
  workflow_call:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Test for Config Server
        run: |
          echo "Building and testing Config Server..."
          cd config-server
          mvn -B package --file pom.xml