name: Discovery Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'discovery/**'
  pull_request:
    branches:
      - main
    paths:
      - 'discovery/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Test for Comment Service
        run: |
          echo "Building and testing Discovery Service..."
          cd discovery
          mvn -B package --file pom.xml