name: API Gateway Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'gateway/**'
  pull_request:
    branches:
      - main
    paths:
      - 'gateway/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/checkout@v4
      - name: Build and Test for Comment Service
        run: |
          echo "Building and testing Gateway Service..."
          cd gateway
          mvn -B package --file pom.xml

  sonar-cloud-analyze:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: SonarCloud Analysis
        run: |
          cd gateway
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tilkata_green-connect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.GATEWAY_SVC_SONAR_TOKEN }}