name: Post Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'post-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'post-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and Test for Post Service
        run: |
          echo "Building and testing Post Service..."
          cd post-service
          mvn -B package --file pom.xml

