name: User Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'user-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'user-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build and Test for User Service
        run: |
          echo "Building and testing User Service..."
          cd post-service
          mvn -B package --file pom.xml


  Create-publish-image-to-dockerhub:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Building an image
        run: |
          cd user-service
          docker build -t user-service .
      - name: Tag the image
        run: |
          docker tag user-service:latest ${{ secrets.DOCKER_USERNAME }}/green-connect:user-service-latest
      - name: Push the image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/green-connect:user-service-latest
          
        
    

